# -*- coding: utf-8 -*-
"""IDS_WebScraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/157mFXcBX8I6iySiynFVlOS8BQePnLJAP
"""

import requests
from bs4 import BeautifulSoup

url = "https://en.wikipedia.org/wiki/Ebookhttps://en.wikipedia.org/wiki/Ebook"
r = requests.get(url)

r.content
#r.status_code
#r.text
#r.headers
#r.headers['Server']

root = BeautifulSoup(r.content, 'html5lib')
print(root.prettify())

table = root.find('table')
print(table)

for i in table.find_all('div', attrs = {'class':'plainlist'}):
  print (table.get_text())

div = table.find('img') 
print(div)


 # quote = {}
  #quote = row['alt'].split(" #")[0]
  #quotes.append(quote)

#for q in quotes:
 # print(q)

for item in div.findAll('a', attrs = {'id':'extiw'}): 
  print(div)

extract = table.find('ul')
print(extract)

reextract = extract.findAll('li')

for items in reextract.find('li'): 
 print(reextract.get_text())